### ISSUE TITLE
Option to fetch own gitignore files (manually created in ~/.ignore-it/gitignores)

### ISSUE THREAD

**Issue by XMasterNinni** [lolcatbois/ignore-it#32]

**Comment by Zerebratox** [comment]
Option to add a ".ignore-it" file in our own "home" directory.

Whenever someone initially adds a .gitignore file to its project, it is also tracked in the ".ignore-it" file.

Whenever someone adds to an existing .gitignore file in its project, it is also tracked in the ".ignore-it" file.

When someone deletes a .gitignore file, and a new one is added, every line of the "ignore-it" file should be deleted and it starts from new.

When someone overwrites the .gitignore file, everything should be deleted again and only the new content should be saved in the "ignore-it" file.
